output: stdout
jobs:
  write_content:
      shell: true
      run: "echo loco >> ./scheduler.txt"
      schedule: run every 1 second
      # schedule: "* * * * * * *"
      output: silent
      tags: ['base', 'infra']

  run_task:
      run: "crawl"
      schedule: "at 10:00 am"
